SET SESSION FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS lodging;
DROP TABLE IF EXISTS authority;
DROP TABLE IF EXISTS comment;
DROP TABLE IF EXISTS love;
DROP TABLE IF EXISTS post;
DROP TABLE IF EXISTS booking;
DROP TABLE IF EXISTS room;
DROP TABLE IF EXISTS user_authority;
DROP TABLE IF EXISTS cancel;
DROP TABLE IF EXISTS coupon;
DROP TABLE IF EXISTS authority;
DROP TABLE IF EXISTS reservation;